mysite/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'', include ('projectone.urls')),
    url(r'^accounts/', include('allauth.urls')),
    
]

projectone/urls.py
from django.conf.urls import url
from . import views


urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^posts_list/$', views.posts_list, name='posts_list'),
    url(r'^base$', views.base, name='base'),
    url(r'^post/(?P<pk>\d+)/$', views.post_detail, name='post_detail'),
    url(r'^post/new/$', views.post_new, name='post_new'),
    url(r'^post/(?P<pk>\d+)/edit/$', views.post_edit, name='post_edit'),
    url(r'^contact/$', views.contactform, name='contact'),
    url(r'^thanks/$', views.thanks, name='thanks'),


]

projectone/models.py
from django.db import models

from django.utils import timezone


class Post(models.Model):
    author = models.ForeignKey('auth.User', on_delete=models.CASCADE)
    title = models.CharField(max_length=200)
    text = models.TextField()
    created_date = models.DateTimeField(
            default=timezone.now)
    published_date = models.DateTimeField(
            blank=True, null=True)

    def publish(self):
        self.published_date = timezone.now()
        self.save()

    def __str__(self):
        return self.title

class Album(models.Model):
    
    img = models.CharField(max_length=120, verbose_name='Файл картинки')
    artist_name = models.CharField(max_length=120, verbose_name='Имя исполнителя')
    album_name = models.CharField(max_length=120, verbose_name='Название альбома')
    release_date = models.DateTimeField(blank=True, null=True, verbose_name='Дата публикации')
    description = models.TextField(verbose_name='Описание')
    index = models.IntegerField(verbose_name='Индекс')
    alt = str(artist_name) + "  " + str(album_name)
    def __unicode__(self):
        return self.title

projectone/forms.py
from django import forms

from .models import Post

class PostForm(forms.ModelForm):

    class Meta:
        model = Post
        fields = ('title', 'text',)


class ContactForm(forms.Form):
    subject = forms.CharField(max_length=100, widget=forms.TextInput(attrs={'size':'40','class': 'form-control'}))
    sender = forms.EmailField(widget=forms.TextInput(attrs={'size':'40','class': 'form-control'}))
    message = forms.CharField(widget=forms.Textarea(attrs={'class': 'form-control'}))
    copy = forms.BooleanField(required=False)

projectone/views.py
from django.shortcuts import render, get_object_or_404,redirect
from django.utils import timezone
from .models import Post
from .forms import PostForm, ContactForm
from .models import Album
from django.http import HttpResponse, HttpResponseRedirect
from django.core.mail import send_mail, BadHeaderError

def index(request):
    albums = Album.objects.order_by('index').all()
    return render(request, 'projectone/index.html', {'albums': albums})

def posts_list(request):
	posts = Post.objects.all()
	return render(request, 'projectone/posts_list.html', {'posts': posts})

def base(request):
	return render(request, 'base.html', {})

def post_detail(request, pk):
    post = get_object_or_404(Post, pk=pk)
    return render(request, 'projectone/post_detail.html', {'post': post})

def post_new(request):
    if request.method == "POST":
        form = PostForm(request.POST)
        if form.is_valid():
            post = form.save(commit=False)
            post.author = request.user
            post.published_date = timezone.now()
            post.save()
            return redirect('post_detail', pk=post.pk)
    else:
        form = PostForm()
    return render(request, 'projectone/post_edit.html', {'form': form})

def post_edit(request, pk):
    post = get_object_or_404(Post, pk=pk)
    if request.method == "POST":
        form = PostForm(request.POST, instance=post)
        if form.is_valid():
            post = form.save(commit=False)
            post.author = request.user
            post.published_date = timezone.now()
            post.save()
            return redirect('post_detail', pk=post.pk)
    else:
        form = PostForm(instance=post)
    return render(request, 'projectone/post_edit.html', {'form': form})

# Функция формы обратной связи
def contactform(reguest):
    if reguest.method == 'POST':
        form = ContactForm(reguest.POST)
        # Если форма заполнена корректно, сохраняем все введённые пользователем значения
        if form.is_valid():
            subject = form.cleaned_data['subject']
            sender = form.cleaned_data['sender']
            message = form.cleaned_data['message']
            copy = form.cleaned_data['copy']

            recepients = ['zhek9kulikov@gmail.com']
            # Если пользователь захотел получить копию себе, добавляем его в список получателей
            if copy:
                recepients.append(sender)
            try:
                send_mail(subject, message, 'zhek9kulikov@gmail.com', recepients)
            except BadHeaderError: #Защита от уязвимости
                return HttpResponse('Invalid header found')
            # Переходим на другую страницу, если сообщение отправлено
            return HttpResponseRedirect('/thanks/')

    else:
        form = ContactForm()
    # Выводим форму в шаблон
    return render(reguest, 'projectone/contact.html', {'form': form})


def thanks(reguest):
    thanks = 'thanks'
    return render(reguest, 'projectone/thanks.html', {'thanks': thanks})

projectone/templates/base.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
  <title>Review</title>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">

  
  <script type="123" src="/static/projectone/js/bootstrap.js"></script>
  <link rel="stylesheet" type="text/css" href="{% static 'projectone/css/bootstrap.css' %}">
  <link rel="stylesheet" type="text/css" href="{% static 'projectone/css/bootstrap-reboot.css' %}">
  <link href= "{% static 'projectone/css/style.css' %}" rel="stylesheet">
</head>
<body>
  <header class="header1">
    <div class="row justify-content-around">
      <div class="col">
        <a class="log" href="/" ><img class="logo" src="/static/projectone/images/review.png"> </a>
      </div>
      <div class="col-6">
        <nav class="navbar nav nav-pills flex-column flex-sm-row">
          <a class="a nav-header flex-sm-fill text-sm-center" href="/posts_list">Post list</a>
          <a class="a nav-header flex-sm-fill text-sm-center" href="/">home</a>
          <a class="a nav-header flex-sm-fill text-sm-center" href="/contact">ContactUs</a>
          {% if user.is_anonymous %}
          <a href="/accounts/login" class="a btn-sm nav-header flex-sm-fill text-sm-center btn btn1 btn-primary" data-toggle="modal" data-target="#login">Login</a>
          <a href="/accounts/signup" class="a btn-sm nav-header flex-sm-fill text-sm-center btn1 btn btn-primary">SignUp</a>
          {% endif %}
          {% if user.is_authenticated %}
          <a href="accounts/logout" class="a btn-sm nav-header flex-sm-fill text-sm-center btn1 btn btn-primary" data-toggle="modal" data-target="#logout">Logout</a>
          <a class="a btn-sm nav-header flex-sm-fill text-sm-center btn1 btn btn-primary" href="{% url 'post_new' %}">new post</a>
          {% endif %}
        </nav>
      </div>
      <div class="col">
        <div class="colabs">
        <a class="edit" href="/">
          <img src="https://img.icons8.com/windows/50/000000/vk-com.png">     
        </a>
        </div>
      </div>
    </div>
  </header>

   <div class="modal fade" id="login" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
       <div class="modal-dialog modal-dialog-centered" role="document">
        <div class="modal-content">
          <div class="modal-header">
            <h5 class="modal-title" id="exampleModalLongTitle">LOGIN</h5>
            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
              <span aria-hidden="true">&times;</span>
            </button>
          </div>
              <div class="modal-body">
                <form class="login" method="POST" action="{% url 'account_login' %}">
                  {% csrf_token %}
                  <div class="form-group">
                    <label for="id_login">Account Name</label>
                    <input type="text" name="login" placeholder="Имя пользователя" autofocus="autofocus" maxlength="150"
                     class="form-control" id="id_login" >
                  </div>
                  <div class="form-group">
                    <label for="id_password">Password</label>
                    <input type="password" name="password" class="form-control" id="id_password" placeholder="Password">
                  </div>
                  <div class="form-group form-check">
                    <input type="checkbox" class="form-check-input" id="exampleCheck1">
                    <label class="form-check-label" for="exampleCheck1">Check me out</label>
                  </div>
                  <div class="modal-footer">
                     <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                     <button type="submit" class="btn btn-primary">Go </button>
                  </div>
                </form>
              </div> 
          </div>
        </div>
      </div>

      <div class="modal fade" id="logout" tabindex="-1" role="dialog" aria-labelledby="logout" aria-hidden="true">
        <div class="modal-dialog" role="document">
          <div class="modal-content">
            <div class="modal-header">
              <h5 class="modal-title" id="exampleModalLabel">Logout</h5>
              <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                <span aria-hidden="true">&times;</span>
              </button>
            </div>
            <div class="modal-body">
              <form method="post" action="{% url 'account_logout' %}">
                {% csrf_token %}
                <div class="form-group">
                  <p>Are you sure you want to quit?<br></p>
                  <button type="submit" class="btn btn-primary">Yes</button>
                   <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                </div>
              </form>
            </div>
          </div>
        </div>
      </div>



{% block content %}
{% endblock %}

<footer class="footer1">
  <div class="container">
  <div class="row justify-content-between">
    <div class="col-4">
      Мы все очень счастливы, я очень рад что у меня получился этот замечательный футер
    </div>
    <div class="col-4">
      А здесь просто контакты, но не переживайте, мы свяжемся с вами сами
    </div>
  </div>
</div>
</footer>


 <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>
  <script src="https://vk.com/js/api/openapi.js?160" type="text/javascript"></script>

</body>
</html>

projectone/templates/index/index.html
  {% extends 'base_template/base_template.html' %}
  {% block content %}
  <div class="wrapper container">
    <article class="container layer-front">
        <h1 class="static">название</h1>
        <h1 class="static">жанр</h1>
        <h1 class="static">страна</h1>
        <h1 class="static">год выпуска</h1>
        <h1 class="static">описание</h1>
    </article>
    <article class="container layer-end">
        <section id="carouselExampleControls" class="layer1 carousel slide" data-ride="carousel">
          <div class="carousel-inner">
            <div class="carousel-item active">
              <div class="container"> 
                <div class="row justify-content-between">
                  <div class="col-4">
                    <img src="/static/images/img1png.png" alt="First slide">
                  </div>
                  <div class="col-4 text-slider border border-dark">
                    <div class="static-item">
                    <h1 class="desc">название</h1>
                    <h1 class="desc">жанр</h1>
                    <h1 class="desc">страна</h1>
                    <h1 class="desc">год выпуска</h1>
                    <h1 class="desc">описание</h1>
                  </div>
                  </div>
                </div>
              </div>
            </div>
           <div class="carousel-item">
              <div class="container"> 
                <div class="row justify-content-between">
                  <div class="col-4">
                    <img src="https://image.freepik.com/free-icon/no-translate-detected_318-1943.jpg" alt="First slide">
                  </div>
                  <div class="col-4 text-slider border border-dark">
                    <h1 class="desc">что-то типа описания</h1>
                  </div>
                </div>
              </div>
            </div>
          </div>
          <a class="carousel-control-prev" href="#carouselExampleControls" role="button" data-slide="prev">
            <span class="carousel-control-prev-icon" aria-hidden="true"></span>
            <span class="sr-only">Previous</span>
          </a>
          <a class="carousel-control-next" href="#carouselExampleControls" role="button" data-slide="next">
            <span class="carousel-control-next-icon" aria-hidden="true"></span>
            <span class="sr-only">Next</span>
          </a>
        </section>
    </article>
  </div>
  {% endblock %}

projectone/templates/posts_list/posts_list.html
{% extends 'base_template/base_template.html' %}
{% block content %}
  {% for post in posts %}
    <div>
        <p>published: {{ post.published_date }}</p>
        <h1><a href="">{{ post.title }}</a></h1>
        <p>{{ post.text|linebreaksbr }}</p>
    </div>
{% endfor %}
{% endblock %}

projectone/templates/projectone/contact.html
{% extends 'base.html' %}

{% block content %}
 
<form action="/contact/" method="post">
    {% csrf_token %}
{#    {% bootstrap_form form %}#}
    {{ form.non_field_errors }}
	<div>
	  <label for="id_subject">Тема:</label>
	  {{ form.subject.errors }}
{#	  {{ form.subject }}#}
      <input class="form-control" id="id_subject" name="subject" placeholder="Тема">
	</div>
    &nbsp;
	<div>
	  <label for="id_sender">E-mail:</label>
	  {{ form.sender.errors }}
{#	  {{ form.sender }}#}
      <input class="form-control" id="id_sender" name="sender" placeholder="Ваш e-mail">
	</div>
    &nbsp;
	<div>
	  <label for="id_message">Сообщение:</label>
	  {{ form.message.errors }}
{#	  {{ form.message }}#}
      <textarea class="form-control" id="id_message" name="message" placeholder="Введите ваше сообщение"></textarea>
	</div>
    &nbsp;
	<div>
	  {{ form.copy.errors }}
	  <label for="id_copy">{{ form.copy }} Отправить копию себе </label>
	</div>
    <br>
	<input type="submit" class="btn btn-success" value="Отправить сообщение"/>
</form>
  </div>
</div>
</div>

{% endblock %}

projectone/templates/projectone/index.html
  {% extends 'base.html' %}
  {% block content %}
  
  <section class="title-site">
    <h1 class="ts">Review - это то место, где вы можете поделиться своим мнением о музыке, которая вам нравится, найти новых друзей и весело провести время</h1>
  </section>
  <div class="wrapper">
    <section>
      <article>
        <div class="row align-items-center">
          <div class="col border-desc">
            <h2 class="tt">Здесь должно быть что-то</h2>
          </div>
          <div class="col border-desc">
            <h2 class="tt">Здесь должно быть что-то</h2>
          </div>
        </div>
      </article>
      <article id="carouselExampleIndicators" class="layer1 carousel slide" data-ride="carousel">
         
          <div class="carousel-inner">
            {% for album in albums %}
            <div class="carousel-item{% ifequal album.index 0 %} active{% endifequal %}">
                <div class="container"> 
                <div class="row justify-content-between">
                  <div class="col-4 imgbase">
                    <img src="/static/projectone/images/{{ album.img }}" alt="{{ album.alt }}">    
                  </div>
                  <div class="col-4 text-slider">
                    <h3 class="text-post"> {{ album.artist_name }}</h3>
                    <h4 class="text-post"> {{ album.album_name }}</h4>
                    <p class="text-post"> {{ album.release_date }}</p>
                    <div class="text"> <p> {{ album.description }} </p></div>
                  </div> 
                </div>
            </div>
          </div>

             {% endfor %}
            
            </div>
          <a class="carousel-control-prev" href="#carouselExampleIndicators" role="button" data-slide="prev">
            <span class="carousel-control-prev-icon" aria-hidden="true"></span>
            <span class="sr-only">Previous</span>
          </a>
          <a class="carousel-control-next" href="#carouselExampleIndicators" role="button" data-slide="next">
            <span class="carousel-control-next-icon" aria-hidden="true"></span>
            <span class="sr-only">Next</span>
          </a>

        


    </section>
  </div>
 {% endblock %}

projectone/templates/projectone/post_detail.html
{% extends 'base.html' %}

{% block content %}
    <div class="wrapper">
        <div class="wrapper-list">
            {% if user.is_authenticated %}
            <a href="{% url 'post_edit' pk=post.pk %}">EDIT POST(она должна быть красивой)</a>
            {% endif %}
            <div class="wrapper-list-content">
                <p class="title-post">Title: {{ post.title }}</p>
                <p class="text-post">Text: {{ post.text|linebreaksbr }}</p>
            </div>
            {% if post.published_date %}
           
                {{ post.published_date }}
            
            {% endif %}
        </div>
    </div>

{% endblock %}

projectone/templates/projectone/posts_list.html
{% extends 'base.html' %}
{% block content %}
  	{% for post in posts %}
	    <div class="wrapper-list">
	    	<div class="wrapper-list-content">
    		<p class="author-post">{{ post.author }}</p>
			<p class="title-post">{{ post.title }}</p>
			<p class="text-post">{{ post.text|linebreaksbr }}</p>
			<small class="data-post">{{ post.published_date }}</small>
			</div>  
	    </div>
	{% endfor %}
{% endblock %}

projectone/templates/projectone/thanks.html
{% extends 'base.html' %}

{% block content %}

 
    <h3>Спасибо, Ваше сообщение отправлено!</h3>
    
{% endblock %}

projectone/templates/projectone/vision.html
         <article id="carouselExampleControls" class="layer1 carousel slide" data-ride="carousel">
        <div class="carousel-inner">
            <div class="carousel-item active">
              <div class="container"> 
                <div class="row justify-content-between">
                  <div class="col-4">
                    <img src="/static/projectone/images/img1png.png" alt="First slide">
                  </div>
                  <div class="col-4 text-slider border border-dark">
                    <h1 class="desc">название</h1>
                    <h1 class="desc">жанр</h1>
                    <h1 class="desc">страна</h1>
                    <h1 class="desc">год выпуска</h1>
                    <h1 class="desc">описание</h1>
                  </div>
                </div>
              </div>
            </div>
           <div class="carousel-item">
              <div class="container"> 
                <div class="row justify-content-between">
                  <div class="col-4">
                    <img src="https://image.freepik.com/free-icon/no-translate-detected_318-1943.jpg" alt="First slide">
                  </div>
                  <div class="col-4 text-slider border border-dark">
                    <h1 class="desc">что-то типа описания</h1>
                  </div>
                </div>
              </div>
            </div>
          </div>
          <a class="carousel-control-prev" href="#carouselExampleControls" role="button" data-slide="prev">
            <span class="carousel-control-prev-icon" aria-hidden="true"></span>
            <span class="sr-only">Previous</span>
          </a>
          <a class="carousel-control-next" href="#carouselExampleControls" role="button" data-slide="next">
            <span class="carousel-control-next-icon" aria-hidden="true"></span>
            <span class="sr-only">Next</span>
          </a>
      </article>

{% endblock %}

'''
    <div id="carousel-generic" class="carousel slide" data-ride="carousel" data-interval="20000" >
  <ol class="carousel-indicators">
    {% for visual in visuals %}
    <li data-target="#carousel-generic" data-slide-to= "{{ visual.index }}" {% ifequal visual.index 0 %} class="active"{% endifequal %}></li>
    {% endfor %}
  </ol>
  <div class="carousel-inner" role="listbox">
    {% for visual in visuals %}
    <div class="item{% ifequal visual.index 0 %} active{% endifequal %}">
      <img style="opacity:0.6; -moz-opacity:0.6; filter: alpha(opacity=60) black; -khtml-opacity: 0.6; -webkit-filter: url(#blur);
      filter: url(#blur); -webkit-filter: blur(3px); filter: blur(3px); filter:progid:DXImageTransform.Microsoft.Blur(PixelRadius='3');
       -webkit-transition: 1s -webkit-filter linear; transition: 1s filter linear;" src="/static/projectone/images/{{ visual.img }}" alt="{{ visual.alt }}">    
    </div>
     <div class="carousel-caption">
     <h3> {{ visual.title }}</h3>
     <p> {{ visual.body }}</p>
     </div>
     
     {% endfor %}
     </div>
  <a class="carousel-control-prev" href="#carousel-generic" role="button" data-slide="prev">
    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
    <span class="sr-only">Previous</span>
  </a>
  <a class="carousel-control-next" href="#carousel-generic" role="button" data-slide="next">
    <span class="carousel-control-next-icon" aria-hidden="true"></span>
    <span class="sr-only">Next</span>
  </a>
    </div>

'''